/*
 * generated by Xtext
 */
package com.dsdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSDLRuntimeModule extends com.dsdl.AbstractDSDLRuntimeModule {

}
