/*
 * generated by Xtext
 */
package com.dsdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.dsdl.ui.internal.DSDLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DSDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DSDLActivator.getInstance().getInjector(DSDLActivator.COM_DSDL_DSDL);
	}
	
}
