/**
 * generated by Xtext
 */
package com.dsdl.ui.contentassist;

import com.dsdl.ui.contentassist.AbstractDSDLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DSDLProposalProvider extends AbstractDSDLProposalProvider {
}
