/**
 * generated by Xtext
 */
package com.dsdl.validation;

import com.dsdl.validation.AbstractDSDLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DSDLValidator extends AbstractDSDLValidator {
}
