/*
 * generated by Xtext
 */
package com.dsdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DSDLUiModule extends com.dsdl.ui.AbstractDSDLUiModule {
	public DSDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
